<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Apple Application Automation Test Sanity Suite" duration-ms="12331" started-at="2018-03-17T10:30:28Z" finished-at="2018-03-17T10:30:40Z">
    <groups>
    </groups>
    <test name="Grid Chrome Test for Apple Application" duration-ms="12331" started-at="2018-03-17T10:30:28Z" finished-at="2018-03-17T10:30:40Z">
      <class name="com.apple.testcases.LoginTestScenario">
        <test-method status="PASS" signature="init(java.lang.String)[pri:0, instance:com.apple.testcases.LoginTestScenario@2cb4c3ab]" name="init" is-config="true" duration-ms="8" started-at="2018-03-17T16:00:28Z" finished-at="2018-03-17T16:00:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="LoginTest(java.lang.String, java.lang.String)[pri:1, instance:com.apple.testcases.LoginTestScenario@2cb4c3ab]" name="LoginTest" duration-ms="9539" started-at="2018-03-17T16:00:28Z" data-provider="UserCredentials" finished-at="2018-03-17T16:00:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[User@1Apple]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Verification Failed expected [Apple] but found [Sign in - Apple]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Verification Failed expected [Apple] but found [Sign in - Apple]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.apple.util.BaseUtil.verifyTitle(BaseUtil.java:301)
	at com.apple.testcases.LoginTestScenario.LoginTest(LoginTestScenario.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="PASS" signature="LoginTest(java.lang.String, java.lang.String)[pri:1, instance:com.apple.testcases.LoginTestScenario@2cb4c3ab]" name="LoginTest" duration-ms="11683" started-at="2018-03-17T16:00:28Z" data-provider="UserCredentials" finished-at="2018-03-17T16:00:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[User@3Apple]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method status="FAIL" signature="LoginTest(java.lang.String, java.lang.String)[pri:1, instance:com.apple.testcases.LoginTestScenario@2cb4c3ab]" name="LoginTest" duration-ms="9551" started-at="2018-03-17T16:00:28Z" data-provider="UserCredentials" finished-at="2018-03-17T16:00:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[User@2Apple]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Verification Failed expected [Apple] but found [Sign in - Apple]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Verification Failed expected [Apple] but found [Sign in - Apple]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.apple.util.BaseUtil.verifyTitle(BaseUtil.java:301)
	at com.apple.testcases.LoginTestScenario.LoginTest(LoginTestScenario.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
      </class> <!-- com.apple.testcases.LoginTestScenario -->
    </test> <!-- Grid Chrome Test for Apple Application -->
  </suite> <!-- Apple Application Automation Test Sanity Suite -->
</testng-results>
